### ISSUE TITLE
Tidy 5e Sheet Rewrite Compatibility

### ISSUE THREAD

**Issue by kgar** [PwQt/magic-items-2#30]
Hello 👋, 
I wanted a chance to discuss with you the possibility of working on compatibility with the [Tidy 5e Sheets rewrite](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/), currently in alpha testing with the community. It is completely rewritten in svelte and will be featuring an API for adding tabs and other content. My sheets are structured differently than the default sheets, e.g., tabs are wired up fairly differently, so I'm in the process of adding the API functions and hooks necessary to support a variety of different sheet-augmenting use cases. 
I am currently looking through this module to see what I might need to offer to make compatibility a matter of a handful of API calls to wire in existing stuff.
Is this something you would be interested in?

**Comment by kgar** [comment]
Update: I've now got the API ready with support for tab registration: https://kgar.github.io/foundry-vtt-tidy-5e-sheets/classes/Tidy5eSheetsApi.html#registerItemTab

There are probably more integration points I'll need to make to fully support integration from this module, but I'm here for it 👍

That being said, I heard the news about COVID. I hope you take care!

**Comment by PwQt** [comment]
[Link](https://github.com/kgar/foundry-vtt-tidy-5e-sheets/issues/116) to the issue on Tidy 5e Sheet Rewrite Project

**Comment by PwQt** [comment]
https://github.com/PwQt/magic-items-2/tree/30-tidy-5e-sheet-rewrite-compatibility created a branch and started work on it,

Currently managed to somewhat show the sheet,
**TODO:**
- DragDrop functionality
- for some reason this radioBoxes throws an exception that something is undefined
```<div class="form-group magic-item-sort">
        <label>{{localize "MAGICITEMS.SheetSortingMode"}}</label>
        <div class="form-fields" style="justify-content: flex-end">
            {{radioBoxes "flags.magicitems.sorting" sortingModes checked=sorting localize=true}}
        </div>
    </div>
```
- probably more template adjustments
- template doesn't receive the default values - Charges are NaN

**Comment by kgar** [comment]
This is exciting! 

I will do my best to help out wherever able.

The tidy item sheet constructor name might change over time, so I have an API function that will insulate you from changes on my side:
![image](https://github.com/PwQt/magic-items-2/assets/4632129/88ae8d7b-c86f-421b-a0a8-de5fc51ed3da)

**Comment by kgar** [comment]
I've got the branch open on my side and am trying some things out. I should have some ideas in a day or so.

**Comment by kgar** [comment]
Here's something I found:
If you'd like to use the magic item data for your handlebars-based tab, you can use the `getData()` option on the tab registration:
![image](https://github.com/PwQt/magic-items-2/assets/4632129/7d649bc2-0194-45a8-b0cc-271dc3241932)

```js
    getData: (data) => {
      return new MagicItem(data.item.flags.magicitems);
    },
```

**Comment by kgar** [comment]
For the `enabled()` option, I recommend including the logic about GMs and hiding from players:

```js
    enabled: (data) => {
      const isSupportedItem = ['weapon', 'equipment', 'consumable', 'tool', 'backpack', 'feat'].includes(data.item.type);
      const isAllowedToShow = game.user.isGM || !game.settings.get(CONSTANTS.MODULE_ID, 'hideFromPlayers');
      return isSupportedItem && isAllowedToShow;
    },
```

**Comment by kgar** [comment]
I have some more ideas for you as I am reading and testing...

In the `render()` function on `magicitemtab.js`, could the show/hide logic and the enabled/disabled logic be done in the handlebars template itself? Since you are already using a Handlebars template, you can fully leverage its features to eliminate manual jquery show/hide/enable/disable post-processing.

![image](https://github.com/PwQt/magic-items-2/assets/4632129/d2ba3f9d-cbd0-4875-a6f7-064a5ed6e6c9)

The `handleEvents()` function on `magicitemtab.js`, I would recommend moving that logic down into the MagicItem class via the `updateItem` hook. You can inspect the item's flag data now that it has been updated, and you can update the MagicItem props accordingly. The benefit here is that you have direct access to your data in the flag, and you do not have to search for your data fields in the HTML. Also, any changes to the HTML should be triggering a re-render by default, so calling render again should hopefully be not needed.

![image](https://github.com/PwQt/magic-items-2/assets/4632129/d8253acf-d8b6-45fb-ae7c-5d7c7da59141)

If you need to transform any of the incoming data, I think you can leverage the `preUpdateItem` hook to review the data and backfill / transform any flags that are not in the right format:

![image](https://github.com/PwQt/magic-items-2/assets/4632129/f964f603-37a0-488f-a91b-4553ca660779)

If these suggestions work as I think they will, you wouldn't even need a `MagicItemTab.bind()` call for Tidy sheets. Then, you could remove Tidy-specific code from your `MagicItemTab` class, keeping it free of my module's influence 😅

**Comment by PwQt** [comment]
> Here's something I found: If you'd like to use the magic item data for your handlebars-based tab, you can use the `getData()` option on the tab registration: ![image](https://private-user-images.githubusercontent.com/4632129/298301539-7d649bc2-0194-45a8-b0cc-271dc3241932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Nzc4NDksIm5iZiI6MTcwNTc3NzU0OSwicGF0aCI6Ii80NjMyMTI5LzI5ODMwMTUzOS03ZDY0OWJjMi0wMTk0LTQ1YTgtYjBjYy0yNzFkYzMyNDE5MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTkwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIzNWZmNjNiYzRjOTk4Yzk4OTVmNzllMzEwMjdmZjM1NzJiZmFjZWNiMTA0YzZiYzllYjcxOTk3YjUzNWM3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bpdwP8ppEbcZ0FDAVdivOTbw12UOHZGaF4c7Q16dVrg)
> 
> ```js
>     getData: (data) => {
>       return new MagicItem(data.item.flags.magicitems);
>     },
> ```
> 
> This may not be the solution to the problem, considering the Magic Item is meant to exist on the MagicItemTab for a long time. However, this is an example of getting the data into the handlebars template.

If I understand the workflow right now it's:
-create the template,
-then do the onRender method?

That's why it's throwing an undefined on the radioBoxes, because it's expecting something to be there?

That's why i'm not a JS dev day-to-day 😅

**Comment by kgar** [comment]
> > Here's something I found: If you'd like to use the magic item data for your handlebars-based tab, you can use the `getData()` option on the tab registration: ![image](https://private-user-images.githubusercontent.com/4632129/298301539-7d649bc2-0194-45a8-b0cc-271dc3241932.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Nzc4NDksIm5iZiI6MTcwNTc3NzU0OSwicGF0aCI6Ii80NjMyMTI5LzI5ODMwMTUzOS03ZDY0OWJjMi0wMTk0LTQ1YTgtYjBjYy0yNzFkYzMyNDE5MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTkwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjIzNWZmNjNiYzRjOTk4Yzk4OTVmNzllMzEwMjdmZjM1NzJiZmFjZWNiMTA0YzZiYzllYjcxOTk3YjUzNWM3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bpdwP8ppEbcZ0FDAVdivOTbw12UOHZGaF4c7Q16dVrg)
> > ```js
> >     getData: (data) => {
> >       return new MagicItem(data.item.flags.magicitems);
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This may not be the solution to the problem, considering the Magic Item is meant to exist on the MagicItemTab for a long time. However, this is an example of getting the data into the handlebars template.
> 
> If I understand the workflow right now it's: -create the template, -then do the onRender method?
> 
> That's why it's throwing an undefined on the radioBoxes, because it's expecting something to be there?
> 
> That's why i'm not a JS dev day-to-day 😅

Ah, welcome to the JS foundry module dev world! I've been here for about 6 months. It is a lot of fun, but there's a lot to learn, whew.

I would love to assist you to a greater degree if you would like, and I can share any knowledge I've gained along the way. If there is a better way to reach you, such as discord or some other chat, I can send more frequent info. Also, I can just post here if you'd like.

For now, let me answer the workflow question. For my sheets, they are running on totally different web tech, so I have to provide a layer of compatibility for handlebars. Here's what my sheets are doing:
- Confirm the template exists and compile it (`path`)
- Check if the template is enabled for this item at this time (`enabled()`)
- Get any data for the handlebars template (`getData()`)
- Render the template to the sheet body where the tab contents should go
- Allow the caller to react to the render event (`onRender()`)

Technically, `onRender()` is only necessary if you need to wire up extra event handling, like if you were to do custom drag and drop handling or some other events that simple input changes do not cover.

In terms of simple data entry, show/hide logic, and enable/disable logic, the Handlebars template can typically cover all of that.

**Comment by kgar** [comment]
If you are ok with it, I can PR to this branch some refactors to help smooth things out for compatibility wiring.

**Comment by PwQt** [comment]
> If you are ok with it, I can PR to this branch some refactors to help smooth things out for compatibility wiring.

Sure, go for it, i planned on sitting some more on it sometime before the weekend.

**Comment by kgar** [comment]
Thanks. I will have you some changes in a day or two. Here are my goals:

- [ ] Remove any references to Tidy Kgar from `magicitemtab.js`; this tab class will likely pertain only to the default and default(like) sheets.
- [ ] Push show/hide enable/disable logic to the templates
- [ ] Evaluate current practices like the magic item instance caching. From what I understand, the Magic Item class is an adapter to surface flag-based values in a useful way
- [ ] Resolve NaN's for the default sheets
- [ ] Checkpoint: Ensuring the existing functionality for the default sheets is still the same as before
- [ ] Wire up Tidy compatibility

I can PR incremental changes to your branch so that we can collaborate and test together. It is all up to your preference as the module owner.

**Comment by kgar** [comment]
The "Items with Spells" library uses the standard sheet HTML for its spell table, so it inherits the default styles without much effort. I propose we do the same in MI2.

This commit demonstrates the alternate structure: https://github.com/PwQt/magic-items-2/pull/46/commits/915c7550a7d9dde919697f5060ac77de659f95f1

**Comment by kgar** [comment]
Hey friends 👋

I have completed my changes for Tidy compatibility. To provide some of the hooks, selectors, and APIs for accomplishing some of the tasks in this process, I released a new version of Tidy 5e sheets, v0.2.16.

In the pull request #46 , I made a handful of simplifications which resulted in possibly fixing #37. I have tested it myself, but maybe someone else can take a look with my changes to confirm.

In the process of standardizing some of the list item table HTML, original Tidy's styles got messed up. Because original Tidy is hopefully retiring later this year, I have patched those broken styles in the MI2 module's CSS file, in the Tidy styles section. I also added styles for New Tidy where it made sense, in the same CSS file.

I found and fixed a number of issues with things parsing as NaN.
I resolved template errors and restored the radio buttons to their original functionality.
I made a number of properties static in places like the MagicItemSheet which needed to be shared.
I resolved some issues that arise when swapping sheets, where a Magic Item class would previously hold onto an instance of the sheet before it was swapped, leading to odd issues.

There's more I'd like to do to help out, but I think it would be better done outside of this one PR, after it's reviewed and vetted.

Latest Tidy Release:
https://github.com/kgar/foundry-vtt-tidy-5e-sheets/releases/tag/v0.2.16
